### ISSUE TITLE
Nesting doesn't work in v1.0.2

### ISSUE THREAD

**Issue by Boris-Scharinger** [IncentroBA/listviewMessageIfEmpty#1]
Hi there, I have a main listview with a listview inside.
Listview inside has a class "noEmptyMessage" attached.
Widget refers to that class.
No matter where I place the widget (inside or outside the main listview, I will only replace the empty message of the first sub listview but nowhere else....
Seems like it gets executed just once and does not attempt to find *any* node with the respective class name...

**Comment by iamrob-nl** [comment]
Hi,

We have been under the impression that you'd want to change a single listview with specific empty messages. So a second listview would feature a different message via another instance of the widget and listen to a different class.

so if I get this right, you want to have all listviews on a page (not all nested) listen to the same class and show the same message?

**Comment by Boris-Scharinger** [comment]
Hi there - yes. While I can't add different class names as the number of sub-listviews is generated by the overarching list view.

**Comment by iamrob-nl** [comment]
I would like to be able to test this situation to improve the widget on it. 
Could you somehow provide me with a test or more info about the amount/size of listview(s) involved?

**Comment by Boris-Scharinger** [comment]
Can you provide me with your email address? I could add you to my project and maybe we schedule a 20min Teams meeting as a walkthrough help.

**Comment by iamrob-nl** [comment]
rob.duits
at
incentro.com
